# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_ajouter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(655, 409)
        self.pushButton_ajouter = QtWidgets.QPushButton(Dialog)
        self.pushButton_ajouter.setGeometry(QtCore.QRect(50, 160, 151, 111))
        self.pushButton_ajouter.setObjectName("pushButton_ajouter")
        self.pushButton_modifier = QtWidgets.QPushButton(Dialog)
        self.pushButton_modifier.setGeometry(QtCore.QRect(250, 160, 151, 111))
        self.pushButton_modifier.setObjectName("pushButton_modifier")
        self.pushButton_suprimmer = QtWidgets.QPushButton(Dialog)
        self.pushButton_suprimmer.setGeometry(QtCore.QRect(440, 160, 151, 111))
        self.pushButton_suprimmer.setObjectName("pushButton_suprimmer")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_ajouter.setText(_translate("Dialog", "Ajouter enclos"))
        self.pushButton_modifier.setText(_translate("Dialog", "Modifier enclos"))
        self.pushButton_suprimmer.setText(_translate("Dialog", "Suprimmer enclos"))
